### ISSUE TITLE
Merge teller cash management functionality

### ISSUE THREAD

**Issue by vishwasbabu** [openMF/mifosx#1184]
The code for cash management is present at:
                https://github.com/binnygopinath/mifosx/tree/cash_mgmt_revised
                https://github.com/binnygopinath/community-app/tree/cash_mgmt_revised
               Branch names for both repositories is: cash_mgmt_revised

**Comment by vorburger** [comment]
@vishwasbabu thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz

**Comment by vorburger** [comment]
@binnygopinath
