### ISSUE TITLE
Clean up https://github.com/openMF/mifosx/pull/1174

### ISSUE THREAD

**Issue by vishwasbabu** [openMF/mifosx#1188]

**Comment by vorburger** [comment]
@vishwasbabu thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
