### ISSUE TITLE
Payment Details for "Frequent Postings" are not stored in the database.

### ISSUE THREAD

**Issue by shadowsnipes** [openMF/mifosx#1217]
I noticed this when I was creating transaction reports that includes the Payment details. Upon closer inspection on the database, I found out that Frequent Postings does not record the payment details.

I tried adding a journal entry using the manual entry "Add Journal Entry" and unlike "Frequent Postings", the entry recorded the payment details.

Is this intended? The "Payment Details" fields are useless if it is.

I would like to record the payment details on Frequent Postings though, since encoding other sources of incomes are easier there compared to the "Add Journal Entry".

I'm still on the process of studying the underlying framework of Mifos X, so I am still relying on manually checking the database instead of the process itself.

I would very much appreciate any help regarding this matter.

**Comment by vorburger** [comment]
@shadowsnipes thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
