### ISSUE TITLE
Failed Import of Loans and savings transaction History to Mifosx 15.03 

### ISSUE THREAD

**Issue by rkatsie** [openMF/mifosx#1388]
The Import tool and new mifos platform are not compatible when importing savings transaction history or Loan transactions history. The templates fail to extract loanpaymenttypeID hence failure to post even though correct ID is enterd

**Comment by vorburger** [comment]
@rkatsie thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
