### ISSUE TITLE
Unable to locate file mentioned in Install.md

### ISSUE THREAD

**Issue by ajinkyagadewar** [openMF/mifosx#1434]
Hello,

I am unable to locate file runmifosx.sh. Can you please help me with correct location of this file?

**Comment by shruthisheshagiri** [comment]
There are known issues with using runmifosx.sh (embedded mariaDB). Please use the classic install instead

**Comment by ajinkyagadewar** [comment]
Okay. I got it working with old mentioned steps.

Sincerely,
Ajinkya Gadewar
