### ISSUE TITLE
API clients sqlSearch logic error

### ISSUE THREAD

**Issue by techkey** [openMF/mifosx#1536]
Please take a look at this code from file `portfolio/client/service/ClientReadPlatformServiceImpl.java` starting at line 162:

``` java
        String extraCriteria = "";
        if (sqlSearch != null) {
            sqlSearch = sqlSearch.replaceAll(" display_name ", " c.display_name ");
            sqlSearch = sqlSearch.replaceAll("display_name ", "c.display_name ");
            extraCriteria = " and (" + sqlSearch + ")";
        }
```

Example `sqlSearch`:

``` sql
status_enum=300 AND display_name LIKE '%k%'
```

Result `extraCriteria`:

``` sql
 and (status_enum=300 AND c.c.display_name LIKE '%k%')
```

That obviously isn't going to work. I've opted to comment out the 2 replacements (replaceAll) and just prefix the column names myself. But this can be easily fixed with a regex or a test to check if the column name already is prefixed. I'm sure the regular coders here have a appropriate solution for this.

**Comment by vorburger** [comment]
@techkey thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
