### ISSUE TITLE
SELECT list is not in GROUP BY clause and contains nonaggregated column

### ISSUE THREAD

**Issue by techkey** [openMF/mifosx#1573]
Quote:
`As of MySQL 5.7.5, the default SQL mode includes ONLY_FULL_GROUP_BY.`

Full article here:
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

That gives problems in file `V118_7__move_withdrawal_annual_fee_to_charges.sql` on line 235, perhaps in more files.

**Comment by theupscale** [comment]
Well, its easy to resolve all you have to do is create a file in your home  directory, where you have to define your my.cnf for mysql and append this 

[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

this will resolve the issue you need to remove the schemas, which is of migration

**Comment by kurdtpage** [comment]
What if someone doesn't have access to my.cnf, like remote hosts such as GoDaddy?

**Comment by maektwain** [comment]
This is an infrastructure issue related to changes done in mysql , either you have to change the query or configuration.

Choice is yours.

**Comment by SeunMatt** [comment]
You can request that mysql 5.5 or 5.6 be provided for you since the changes started with mysql 5.7

**Comment by vorburger** [comment]
@techkey thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
