### ISSUE TITLE
HTTP 204 Response, while creating Survey ScoreCard

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mifosx#1622]
Demo Server giving 204 response when submitting POST Request to [https://demo.openmf.org/fineract-provider/api/v1/surveys/3/scorecards](url) with Json Object

``` json
{
  "userId": 1,
  "clientId": 9,
  "createdOn": "2016-03-29T19:31:48.094Z",
  "scorecardValues": [
    {
      "questionId": 21,
      "responseId": 77,
      "value": 0
    },
    {
      "questionId": 22,
      "responseId": 86,
      "value": 2
    },
    {
      "questionId": 23,
      "responseId": 89,
      "value": 7
    },
    {
      "questionId": 24,
      "responseId": 92,
      "value": 4
    },
    {
      "questionId": 25,
      "responseId": 97,
      "value": 2
    },
    {
      "questionId": 26,
      "responseId": 102,
      "value": 3
    },
    {
      "questionId": 27,
      "responseId": 104,
      "value": 3
    },
    {
      "questionId": 28,
      "responseId": 106,
      "value": 6
    },
    {
      "questionId": 29,
      "responseId": 110,
      "value": 7
    },
    {
      "questionId": 30,
      "responseId": 113,
      "value": 7
    }
  ]
}
```

Where:
createdOn is the current date in the standard form "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

**Note : There is no ScoreCard adding into database !**
Beacuse When submitting GET Request to the 
[https://demo.openmf.org/fineract-provider/api/v1/surveys/3/scorecards](url).
The Response list is null([])

Reference : [https://demo.openmf.org/api-docs/apiLive.htm#scorecards_create](url),
[https://demo.openmf.org/api-docs/apiLive.htm#scorecards_list](url)

**Comment by bnasim** [comment]
There is issue in Survey API, POST Scorecard doesn't work. You can check in POSTMAN, it was throwing constraint violation error.

**Comment by vorburger** [comment]
@therajanmaurya thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
