### ISSUE TITLE
Fix the broken unnecessarily complex installation process

### ISSUE THREAD

**Issue by openqubit** [openMF/mifosx#1626]
The installation process is broken and needs fixing. The automated process particularly needs urgent attention. Once you install via automated system never starts

**Comment by vorburger** [comment]
@ openqubit thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
