### ISSUE TITLE
about the developer guide

### ISSUE THREAD

**Issue by AnaghHegde** [openMF/mifosx#1631]
Hi i am new to here.But i am facing the following issues.
The link to the Developers wiki page,Getting started ,Overview of platform are not  working.Either they have deen removed or deleted.I am getting this Page Not Found when i go to that link.

Someone please help me out.I am very interested in contributing to opensource.

**Comment by vorburger** [comment]
@AnaghHegde thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
