### ISSUE TITLE
Whitelabel error

### ISSUE THREAD

**Issue by kaitesi** [openMF/mifosx#1636]
Dear all,
Greetings!! 
I recently installed mifos x version 17.07.01 but i am unable to run it in the browser as it gives an error message.  
![white](https://user-images.githubusercontent.com/9653132/36729821-5cd87146-1bbd-11e8-95dc-8a6432afd797.png)

kindly help me

**Comment by SeunMatt** [comment]
The error is 404 - page missing.

How did you start the application server? by running `./gradlew clean tomcatrunwar` ? 

The to verify your application is running goto `https://localhost:8443/fineract-provider/api/v1/offices`
from your browser which should prompt you for credentials use **mifos** as username and **password** as password

Cheers

**Comment by vorburger** [comment]
@kaitesi thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
