### ISSUE TITLE
local host refused to connect

### ISSUE THREAD

**Issue by anmh4** [openMF/mifosx#1637]
I installed mifos x from official site but at the end it is not connecting with localhost. localhost refused to connect with it..can any one give me solution how to resolve this problem..?

**Comment by SeunMatt** [comment]
What's the error message? and what steps have you followed? Please provide more information

**Comment by vorburger** [comment]
@anmh4 thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
