### ISSUE TITLE
Error Installing: Unable to obtain Jdbc connection from DataSource; for Tenant DB URL: 

### ISSUE THREAD

**Issue by obaqueiro** [openMF/mifosx#1638]
Sorry if this is the wrong place to post this. If that's the case, please provide a link to the correct forum to post this question.

I am trying to install Fineract following the link at [Fineract-101](https://cwiki.apache.org/confluence/display/FINERACT/Fineract+101).

So far,  I have succesfully installed Tomcat7 (I get tomcat welcome page in my 443 localhost port). I have compiled the war file (fineract-provider.war), I have installed mysql-server and triple checked credential files.

When I copy the WAR file to webapps/ and start tomcat, the Fineract application is not deployed, but instead several errors are thrown. 

- [The full catalina.log output. ](https://pastebin.com/92wschi4)
- [My server.xml config](https://pastebin.com/58schdZi)
- [The MySQL schemas listing](https://pastebin.com/1m8FyE5F)

The first concrete error I see in the catalina logs is: 
>Unable to obtain Jdbc connection from DataSource; for Tenant DB URL: jdbc:mysql:thin://localhost:3306/mifostenant-default, username: root

Which makes me thing that this is a DB configuration issue. However, I **have** checked the server.xml db configuration and ensured that it matches with the root configuration.  I am affraid other stuff in the log does not make sense.  
Any help will be appreciated.

**Comment by SeunMatt** [comment]
is this `jdbc:mysql:thin://localhost:3306/mifostenant-default` not supposed to be this `jdbc:mysql://localhost:3306/mifostenant-default` ? **note the thin part.**

**Comment by vorburger** [comment]
@obaqueiro thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
