### ISSUE TITLE
Archive this project!

### ISSUE THREAD

**Issue by vorburger** [openMF/mifosx#1641]
252ca0cd7c42ea187ffd1e066bef03eb2497fd75 does not seem to be clear enough, given #1640 ...

... which should Archive this project (via that button in GitHub Settings).

Who has admin permission on this project to do that?

**Comment by vorburger** [comment]
https://help.github.com/articles/archiving-a-github-repository/

https://github.blog/2017-11-08-archiving-repositories/

**Comment by vishwasbabu** [comment]
@vorburger:  I have archived the project and also added you as a project Admin.
@edcable : I was under the impression that the Mifos Initiative was pulling in the latest Fineract code with every release, adding Pentaho reports and making a separate MifosX release.
