### ISSUE TITLE
Periodic Moratorium On principal payment

### ISSUE THREAD

**Issue by jiron12** [openMF/mifosx#897]
Dear MIFOS Comnunity
Here is another issue we'd like to raise.

Situation
We have many clients with revenue that is heavily depending on the season of the year. For example farmers, beekeepers or pavers. For these we need the possibility to pay back, for example in some winter months, the interest only.

![periodicmoratorium](https://cloud.githubusercontent.com/assets/7449514/2903388/7bdc4b60-d5f0-11e3-949b-b213611f9469.png)

Approach
With my limited knowledge about MIFOS I can think of one general approach to achieve this, ...my two cents:

Define on loan creation something like "Periodic Moratorium On principal payment" similar to  "Moratorium On principal payment". Where one could select/deselect months/weeks/days according to "Repaid every". Of course the same could consequently be made on Interest and Arrears Ageing.

I am aware of the fact that, whichever way to solve it, this might be no small thing. But our clients indeed want and need I schedule like that. So we thought we'd just ask.

Thank you very much for considering!
Joel

**Comment by vorburger** [comment]
@jiron12 thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
